name = "TransmuteDims"
uuid = "24ddb15e-299a-5cc3-8414-dbddc482d9ca"
authors = ["Michael Abbott"]
version = "0.0.1"

[deps]

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
